version: "2.3"

networks:
  sa_network:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    networks:
      - sa_network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: "4g"
  
  kibana:
    image: kibana:8.8.1
    container_name: kibana
    networks:
      - sa_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  monstache:
    image: rwynn/monstache:latest
    container_name: monstache
    networks:
      - sa_network
    volumes:
      - ./config/config.toml:/root/config.toml
    command: -f /root/config.toml
    depends_on:
      - elasticsearch
      - mongo
      - mongo1
      - mongo2
      - mongo-init
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - sa_network
    ports:
      - "27017:27017"
    command: mongod --replSet rp0

  mongo1:
    image: mongo:latest
    container_name: mongo1
    networks:
      - sa_network
    expose:
      - 27017
    ports:
      - "27018:27017"
    command: mongod --replSet rp0
    depends_on:
      - mongo

  mongo2:
    image: mongo:latest
    container_name: mongo2
    networks:
      - sa_network
    expose:
      - 27017
    ports:
      - "27019:27017"
    command: mongod --replSet rp0
    depends_on:
      - mongo

  mongo-init:
    restart: "no"
    image: mongo:latest
    container_name: mongo-init
    networks:
      - sa_network
    volumes:
      - ./config/init.js:/root/init.js
    command: bash -c "sleep 3 && mongosh --host mongo:27017 /root/init.js"
    depends_on:
      - mongo
      - mongo1
      - mongo2

  springboot:
    build:
      context: .
      dockerfile: ./config/springboot/Dockerfile
    container_name: springboot
    networks:
      - sa_network
    ports:
      - "8080:8090"
    volumes:
      - ./libs:/jlib
      - ./build/libs:/volume
    environment:
      - LD_LIBRARY_PATH=/jlib
    command: java -jar /volume/school_assignment-0.0.1-SNAPSHOT.jar --spring.data.mongodb.uri="mongodb://mongo:27017/school_assignment?retryWrites=false&directConnection=true"
    depends_on:
      - mongo
      - mongo1
      - mongo2
